---
Parameters:
   SecurityGroupDescription:
      Description: Security Group Description
      Type: String
      
Resources:
   MyInstance:
      Type: AWS::EC2::Instance
      Properties:
         AvailabilityZone: us-east-1a
         ImageId: ami-a4c7edb2
         InstanceType: t2.micro
         SecurityGroups:
            - !Ref SSHSecurityGroup
            - !Ref ServerSecurityGroup
            
   # un elastic Ip para la instancia
   MyEIP:
      Type: AWS::EC2::EIP
      Properties:
         InstanceId: !Ref MyInstance
         
   #nuestro EC2 security group
   SSHSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
         GroupDescription: Enable SSH acces via port 22
         SecurityGroupIngress:
         - CidrIp: 0.0.0.0/0
           FromPort: 22
           IpProtocol: tcp
           ToPort: 22
           
   #nuestro segundo EC2 security group
   ServerSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
         GroupDescription: !Ref SecurityGroupDescription
         SecurityGroupIngress:
         - IpProtocol: tcp
           FromPort: 80
           ToPort: 80
           CidrIp: 0.0.0.0/0
         - IpProtocol: tcp
           FromPort: 22
           ToPort: 22
           CidrIp: 192.168.1.1/32 
      